# Generated by Django 5.2.3 on 2025-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='bikes/')),
                ('buy_url', models.URLField(blank=True, null=True)),
                ('read_more_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
