# Generated by Django 5.2.3 on 2025-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='mission_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vision_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='vision_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='vision_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='buy_url',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='read_more_url',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='title',
        ),
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
