# Generated by Django 5.2.3 on 2025-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_arrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='vision_images/'),
        ),
    ]
