# Generated by Django 5.2.3 on 2025-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_vision_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrow',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='arrow_backgrounds/'),
        ),
    ]
