# Generated by Django 5.2.3 on 2025-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_arrow_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_cc', models.CharField(max_length=50)),
                ('kilometers', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('ownership', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('image_data', models.BinaryField()),
                ('image_type', models.CharField(default='image/jpeg', max_length=50)),
            ],
        ),
    ]
