# Generated by Django 5.2.3 on 2025-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_biki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biki',
            name='image_data',
        ),
        migrations.AddField(
            model_name='biki',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biki',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biki',
            name='engine_cc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='biki',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biki',
            name='image_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biki',
            name='kilometers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='biki',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biki',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biki',
            name='ownership',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='biki',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
