# Generated by Django 5.2.3 on 2025-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_remove_biki_image_data_biki_image_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biki',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
