# Generated by Django 5.2.3 on 2025-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_biki_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='biki',
            name='engine_type',
            field=models.CharField(default='FTS', max_length=50),
        ),
    ]
