# Generated by Django 5.2.3 on 2025-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0010_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subtext', models.TextField()),
                ('image', models.ImageField(upload_to='hero_images/')),
            ],
        ),
    ]
