# Generated by Django 5.2.3 on 2025-09-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0012_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
