# Generated by Django 5.2.3 on 2025-09-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0013_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='chango_backgrounds/')),
            ],
        ),
    ]
