# Generated by Django 5.2.3 on 2025-09-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0015_approach_approachimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='image',
            field=models.ImageField(default='', upload_to='approach_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approach',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ApproachImage',
        ),
    ]
