# Generated by Django 5.2.3 on 2025-09-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0016_approach_image_alter_approach_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.CharField(choices=[('general', 'General Enquiry'), ('buy', 'Buy a Bike'), ('sell', 'Sell a Bike'), ('exchange', 'Exchange a Bike'), ('rto', 'RTO Service'), ('others', 'Others')], max_length=20)),
                ('found_us', models.CharField(choices=[('olx', 'OLX'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('google', 'Google'), ('website', 'Website'), ('facebook', 'Facebook'), ('walkin', 'Walk-in')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
