# Generated by Django 5.2.3 on 2025-09-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0017_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
