# Generated by Django 5.2.3 on 2025-09-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0018_bikead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
