# Generated by Django 5.2.3 on 2025-09-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0019_processstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='image_url',
        ),
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.ImageField(default='', upload_to='process_steps/'),
            preserve_default=False,
        ),
    ]
