# Generated by Django 5.2.3 on 2025-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0020_remove_processstep_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('engine_cc', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('kilometers', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('owner_info', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
