# Generated by Django 5.2.3 on 2025-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0021_bikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
