# Generated by Django 5.2.3 on 2025-09-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0022_bikes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='image',
        ),
    ]
