# Generated by Django 5.2.3 on 2025-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0024_bikes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes_images/'),
        ),
    ]
