# Generated by Django 5.2.3 on 2025-09-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0025_alter_bikes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike2_images/'),
        ),
    ]
