# Generated by Django 5.2.3 on 2025-09-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0029_alter_bikes_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
