# Generated by Django 5.2.3 on 2025-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0031_alter_bikes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('make_year', models.IntegerField()),
                ('refurbished', models.BooleanField(default=False)),
                ('rto_state', models.CharField(blank=True, max_length=100)),
                ('rto_city', models.CharField(blank=True, max_length=100)),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('kilometers', models.PositiveIntegerField()),
                ('owners', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('registration_certificate', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('warranty', models.BooleanField(default=False)),
                ('bike_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('ignition_type', models.CharField(blank=True, max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('front_brake_type', models.CharField(max_length=50)),
                ('rear_brake_type', models.CharField(max_length=50)),
                ('abs', models.BooleanField(default=False)),
                ('odometer', models.CharField(max_length=50)),
                ('wheel_type', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
