# Generated by Django 5.2.3 on 2025-09-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0032_bikesdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikesdetail',
            old_name='make_year',
            new_name='year',
        ),
    ]
