# Generated by Django 5.2.3 on 2025-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0033_rename_make_year_bikesdetail_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='booking_steps/')),
                ('order', models.IntegerField()),
            ],
        ),
    ]
