# Generated by Django 5.2.3 on 2025-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0034_bookingstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='login_images/')),
            ],
        ),
    ]
