# Generated by Django 5.2.3 on 2025-09-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0035_loginimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginImage',
        ),
    ]
