# Generated by Django 5.2.3 on 2025-09-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0038_loginpageasset_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='LoginPageAsset',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
