# Generated by Django 5.2.3 on 2025-09-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0039_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='login_images/')),
            ],
        ),
    ]
